# Generated by Django 4.1.5 on 2023-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('salaryYear', models.IntegerField(verbose_name='Средняя зарплата')),
                ('numberVacancies', models.IntegerField(verbose_name='Средняя зарплата для выбранной профессии')),
                ('selectedSalaryYear', models.IntegerField(verbose_name='Количество вакансий')),
                ('selectedNumberVacancies', models.IntegerField(verbose_name='Количество вакансий для выбранной профессии')),
                ('skills', models.TextField(verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
            },
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
