# Generated by Django 4.1.5 on 2023-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testin', '0002_years_alter_profession_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='salaryCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('salary', models.IntegerField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Города по зарплатам',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='vacanciesCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('vacancies', models.FloatField(verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Города по кол-ву вакансий',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.AlterField(
            model_name='years',
            name='numberVacancies',
            field=models.IntegerField(verbose_name='Количество вакансий'),
        ),
        migrations.AlterField(
            model_name='years',
            name='selectedSalaryYear',
            field=models.IntegerField(verbose_name='Средняя зарплата для выбранной профессии'),
        ),
    ]
